[global]
db_url="localhost:26257/bidder"
prover_url="localhost:50052"

[chain]
chain_id=421614
#chain_rpc="https://arbitrum-sepolia.infura.io/v3/5c0a76697f86492c8a335c888ca9f670"
chain_rpc="https://arbitrum-sepolia-rpc.publicnode.com"
blk_interval=1
blk_delay=1
max_blk_delta=5000
forward_blk_delay=500
brevis_market_addr="0x7c968e3b1FaE6599958104cbf40d17A4ba0c1d43"
prover_eth_addr=""
submitter_keystore=""
submitter_passphrase=""

[rule]
max_fee="1000000000000000000000000000000000"
max_input_size=0
prover_gas_price="1"
prove_min_duration=3600
vk_whitelist=[]
vk_blacklist=[]